# utterances comments configuration
comments:
  repo: sut-ai/comments
  issue_term: pathname
  issue_label: comments
  theme: github-light
  crossorigin: anonymous

# google analytics configuration
google_analytics_id: G-VZRZHCJ5V0
